### ISSUE TITLE
Why use bwa mem  to align the sequence？

### ISSUE THREAD

**Issue by WellJoea** [smithlabcode/smurfseq_scripts#6]
Why donot use the long-reads alignment software, such as  minimap2, graphmap and ngmlr?
What is the advantage of bwa mem? In other words, can I use the monimap2 to get the sam/bam file for smurfseq

**Comment by andrewdavidsmith** [comment]
I don’t see a bug or a feature request here, or anything about the software as written (or even anything specific at all). The published paper on SMURF-seq has contact information for such questions.
